# Generated by Django 5.2.1 on 2025-07-01 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tipogasto_remove_doctor_duracion_cita_and_more'),
        ('doctor', '0005_remove_atencion_doctor_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='citamedica',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='condicion',
            field=models.CharField(blank=True, choices=[('hipertension', 'Hipertensión'), ('diabetes', 'Diabetes'), ('control_rutinario', 'Control Rutinario'), ('cardiologia', 'Cardiología'), ('seguimiento', 'Seguimiento'), ('neurologia', 'Neurología'), ('ginecologia', 'Ginecología'), ('ortopedia', 'Ortopedia'), ('dermatologia', 'Dermatología'), ('oftalmologia', 'Oftalmología'), ('artritis', 'Artritis')], help_text='Motivo principal o condición del paciente para esta cita.', max_length=50, null=True, verbose_name='Condición o Motivo de la Cita'),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_por_especialidad', to='core.especialidad', verbose_name='Especialidad de la Cita'),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_agendadas', to='core.doctor', verbose_name='Médico Asignado'),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='tipo_cita',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('normal', 'Normal'), ('seguimiento', 'Seguimiento')], default='normal', help_text='Clasificación de la prioridad o propósito de la cita.', max_length=15, verbose_name='Tipo de Cita'),
        ),
        migrations.AlterUniqueTogether(
            name='citamedica',
            unique_together={('fecha', 'hora_cita', 'medico')},
        ),
        migrations.AddIndex(
            model_name='citamedica',
            index=models.Index(fields=['medico', 'fecha', 'hora_cita'], name='idx_medico_fecha_hora'),
        ),
        migrations.AddIndex(
            model_name='citamedica',
            index=models.Index(fields=['especialidad'], name='idx_especialidad'),
        ),
        migrations.AddIndex(
            model_name='citamedica',
            index=models.Index(fields=['tipo_cita'], name='idx_tipo_cita'),
        ),
        migrations.AddIndex(
            model_name='citamedica',
            index=models.Index(fields=['estado'], name='idx_estado_cita'),
        ),
    ]
