# Generated by Django 5.2.1 on 2025-07-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_citamedica_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citamedica',
            name='condicion',
            field=models.CharField(blank=True, choices=[('hipertension', 'Hipertensión'), ('diabetes', 'Diabetes'), ('control_rutinario', 'Control Rutinario'), ('cardiologia', 'Cardiología'), ('seguimiento', 'Seguimiento'), ('neurologia', 'Neurología'), ('ginecologia', 'Ginecología'), ('ortopedia', 'Ortopedia'), ('dermatologia', 'Dermatología'), ('oftalmologia', 'Oftalmología'), ('artritis', 'Artritis'), ('infeccion_respiratoria', 'Infeccion respiratoria'), ('otorrinolaringologia', 'Otorrinolaringología'), ('pediatria', 'Pediatría'), ('gastroenterologia', 'Gastroenterología')], help_text='Motivo principal o condición del paciente para esta cita.', max_length=50, null=True, verbose_name='Condición o Motivo de la Cita'),
        ),
    ]
