# Generated by Django 5.2.1 on 2025-07-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_alter_citamedica_condicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepago',
            name='valor_consulta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor de consulta proveniente del pago seleccionado.', max_digits=10, null=True, verbose_name='Valor de consulta'),
        ),
    ]
