# Generated by Django 5.2.1 on 2025-07-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_alter_citamedica_condicion'),
        ('doctor', '0007_detallepago_valor_consulta'),
    ]

    operations = [
    ]
