# Generated by Django 5.2.1 on 2025-07-04 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_merge_20250703_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago_global',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se procesó el pago desde el modal.', verbose_name='Fecha de Procesamiento')),
                ('metodo_pago_modal', models.CharField(help_text='Método de pago seleccionado en el modal (Efectivo, Tarjeta de Crédito/Débito, PayPal).', max_length=50, verbose_name='Método de Pago')),
                ('observaciones_procesamiento', models.TextField(blank=True, help_text='Observaciones adicionales capturadas durante el procesamiento del pago.', null=True, verbose_name='Observaciones del Procesamiento')),
                ('estado_procesamiento', models.CharField(choices=[('procesado', 'Procesado'), ('pendiente', 'Pendiente'), ('fallido', 'Fallido'), ('cancelado', 'Cancelado')], default='procesado', max_length=20, verbose_name='Estado del Procesamiento')),
                ('monto_procesado', models.DecimalField(decimal_places=2, help_text='Monto que fue efectivamente procesado en el modal.', max_digits=10, verbose_name='Monto Procesado')),
                ('usuario_procesamiento', models.CharField(blank=True, help_text='Usuario que procesó el pago desde el modal.', max_length=100, null=True, verbose_name='Usuario que Procesó')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('detalle_pago', models.ForeignKey(help_text='Detalle del pago asociado a este registro global.', on_delete=django.db.models.deletion.CASCADE, related_name='pagos_globales', to='doctor.detallepago', verbose_name='Detalle de Pago')),
            ],
            options={
                'verbose_name': 'Pago Global',
                'verbose_name_plural': 'Pagos Globales',
                'ordering': ['-fecha_procesamiento'],
            },
        ),
    ]
