# Generated by Django 5.2.1 on 2025-07-04 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_detallepago_valor_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='atencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='doctor.atencion', verbose_name='Atención'),
        ),
        migrations.CreateModel(
            name='Pago_global',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procesado_desde_modal', models.BooleanField(default=True, help_text='Indica si este pago fue procesado desde el modal de gestión.', verbose_name='Procesado desde Modal')),
                ('datos_procesamiento', models.JSONField(blank=True, default=dict, help_text='Información adicional del procesamiento (PayPal, etc.)', verbose_name='Datos de Procesamiento')),
                ('referencia_externa', models.CharField(blank=True, help_text='Referencia externa específica del pago global', max_length=100, null=True, verbose_name='Referencia Externa Global')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('pago', models.OneToOneField(help_text='Pago principal asociado a este registro global.', on_delete=django.db.models.deletion.CASCADE, related_name='pago_global', to='doctor.pago', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Pago Global',
                'verbose_name_plural': 'Pagos Globales',
                'ordering': ['-pago__fecha_creacion'],
            },
        ),
    ]
