# Generated by Django 5.2.1 on 2025-07-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_pago_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago_global',
            name='referencia_externa',
            field=models.CharField(blank=True, help_text='ID de transacción PayPal u otra referencia externa del pago.', max_length=100, null=True, verbose_name='Referencia Externa'),
        ),
    ]
