# Generated by Django 5.2.1 on 2025-07-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_restructure_pago_global'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago_global',
            options={'ordering': ['-fecha_pago'], 'verbose_name': 'Pago Global', 'verbose_name_plural': 'Pagos Globales'},
        ),
        migrations.AlterField(
            model_name='pago_global',
            name='fecha_pago',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se procesó el pago.', verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='pago_global',
            name='metodo_pago',
            field=models.CharField(help_text='Método de pago seleccionado (Efectivo, Tarjeta de Crédito/Débito, PayPal).', max_length=50, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='pago_global',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, help_text='Monto total del pago procesado.', max_digits=10, verbose_name='Monto Total'),
        ),
        migrations.AlterField(
            model_name='pago_global',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones adicionales del pago.', null=True, verbose_name='Observaciones'),
        ),
    ]
