# Generated by Django 4.2.11 on 2025-01-04 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_alter_pago_global_options_and_more'),
    ]

    operations = [
        # Primero agregar la columna pago_id como nullable
        migrations.AddField(
            model_name='pago_global',
            name='pago',
            field=models.OneToOneField(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='pago_global',
                to='doctor.pago',
                verbose_name='Pago',
                help_text='Pago principal asociado a este registro global.'
            ),
        ),
        
        # Luego eliminar los campos obsoletos
        migrations.RemoveField(
            model_name='pago_global',
            name='paciente_nombre',
        ),
        migrations.RemoveField(
            model_name='pago_global',
            name='paciente_identificacion',
        ),
        migrations.RemoveField(
            model_name='pago_global',
            name='paciente_email',
        ),
        migrations.RemoveField(
            model_name='pago_global',
            name='paciente_telefono',
        ),
        migrations.RemoveField(
            model_name='pago_global',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pago_global',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='pago_global',
            name='monto_total',
        ),
        migrations.RemoveField(
            model_name='pago_global',
            name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='pago_global',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='pago_global',
            name='atencion',
        ),
        
        # Agregar nuevos campos
        migrations.AddField(
            model_name='pago_global',
            name='procesado_desde_modal',
            field=models.BooleanField(
                default=True,
                verbose_name='Procesado desde Modal',
                help_text='Indica si este pago fue procesado desde el modal de gestión.'
            ),
        ),
        migrations.AddField(
            model_name='pago_global',
            name='datos_procesamiento',
            field=models.JSONField(
                default=dict,
                blank=True,
                verbose_name='Datos de Procesamiento',
                help_text='Información adicional del procesamiento (PayPal, etc.)'
            ),
        ),
        
        # Finalmente, hacer que pago_id sea obligatorio
        migrations.AlterField(
            model_name='pago_global',
            name='pago',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='pago_global',
                to='doctor.pago',
                verbose_name='Pago',
                help_text='Pago principal asociado a este registro global.'
            ),
        ),
    ]
