# Generated by Django 4.2.11 on 2025-01-04 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_fix_pago_global_structure'),
    ]

    operations = [
        # Cambiar la relación de Pago con Atencion de PROTECT a CASCADE
        migrations.AlterField(
            model_name='pago',
            name='atencion',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='pagos',
                to='doctor.atencion',
                verbose_name='Atención'
            ),
        ),
    ]
