# Generated by Django 5.2.1 on 2025-07-04 06:54

import django.db.models.deletion
import django.views.generic.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_alter_audituser_accion'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModulePermissionListView',
            fields=[
                ('groupmodulepermission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='security.groupmodulepermission')),
            ],
            bases=('security.groupmodulepermission', django.views.generic.base.TemplateView),
        ),
    ]
